server:
  port: 8282
http:
  logging:
    enabled: true
    log-body: true
    log-level: warn
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: book-service
